##############################################################################
# (c) Crown copyright 2024 Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
##############################################################################

# This input file can be generated by running the:
# lfric_atm test suite
# It is generated by the ral3-seuk_ls_and_jedi test
INPUT=seuk_lfric_bg_for_hofx.nc
OUTPUT=seuk_jedi_trajectory.nc

TIMESTEP=$(ncks -d time_counter,0 -v time_instant ${INPUT} | grep "time_instant =" | sed -e "s/.*= //;s/ .*//"  | tr -d -c 0-9)

echo Shifting time back by ${TIMESTEP}
# Change the file so that the time starts at 0
ncap2 -O -s time_instant-=${TIMESTEP} ${INPUT} ${INPUT}_tmp
ncap2 -O -s time_instant_bounds-=${TIMESTEP} ${INPUT}_tmp ${OUTPUT}
rm *tmp*
echo Output ${OUTPUT}
