[file:iodef.xml]
source=$ROSE_SUITE_DIR/app/lfric_atm/file/iodef_gal_nwp_nudging.xml

[namelist:external_forcing]
pc2_force_response=.false.
theta_forcing='nudging'
wind_forcing='nudging'

[namelist:files]
nudging_directory='/data/users/mohit.dalvi/lfric/data/nudge/era/C48'
nudging_filename='era5_nudge_L137_C48_MG_2021032400-2706'

[namelist:multires_coupling]
aerosol_mesh_name='dynamics'
coarse_nudging=.false.
coarse_rad_aerosol=.false.
lowest_order_aero_flag=.false.
multires_coupling_mesh_tags='dynamics'
nudging_mesh_name='dynamics'
orography_mesh_name='dynamics'
physics_mesh_name='dynamics'

[namelist:nudging]
nudge_data_levels=137
nudging_level_bottom=5
nudging_level_top=52
nudging_source='era'
nudging_width_bottom=1
nudging_width_top=0

[namelist:section_choice]
external_forcing=.true.
